# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-28 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photohost', '0002_auto_20161226_1739'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_owner', models.CharField(max_length=200)),
                ('album_title', models.CharField(max_length=200)),
                ('album_cover', models.CharField(max_length=1000)),
            ],
        ),
    ]
